// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROuIhCnGPAgUZDAAYoAN3Tn1WbUjE-iw',
    appId: '1:637317927011:web:f9be0c5f62a8a94a16e856',
    messagingSenderId: '637317927011',
    projectId: 'cbc-online-e9847',
    authDomain: 'cbc-online-e9847.firebaseapp.com',
    storageBucket: 'cbc-online-e9847.appspot.com',
    measurementId: 'G-DEYSZD06CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqDcKEtZpeO0txL504ODTSpRjuVjPZNl0',
    appId: '1:637317927011:android:1fe0186963c4e7d416e856',
    messagingSenderId: '637317927011',
    projectId: 'cbc-online-e9847',
    storageBucket: 'cbc-online-e9847.appspot.com',
  );
}
